spring:
  profiles:
    include: oauth2, db, jwt
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}
    url: ${url}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-id}
            client-secret: ${google-secret}
            scope:
              - email
              - profile
          naver:
            client-id: ${naver-id}
            client-secret: ${naver-secret}
            client-name: Naver
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: ${kakao-id}
            client-secret: ${kakao-secret}
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  issuer: ${issuer}
  secret_key: ${secret_key}