spring:
  datasource:
    url: jdbc:mysql://kkini-db.cvgljaoehvqz.ap-northeast-2.rds.amazonaws.com:3306/test?useSSL=false
    username_: admin
    password: doma6591
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false