name: Spring Boot EC2 Deployment

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
      
    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_URL }}
        username: 'ubuntu'
        key: ${{ secrets.DEPLOY_KEY }}
        source: "./target/*.jar"
        target: "~/backend"
      
    - name: Login to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_URL }}
        username: 'ubuntu'
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ~/backend
          docker build -t backend .
          docker stop backend || true
          docker run --rm -d -p 80:8080 --name backend backend
